#!/bin/bash
apt install python python2 -y
pip install requests
apt install tor -y
apt install openssl openssl-tool -y
apt install php -y
apt install jq -y
gem install tail 
gem install lolcat
apt install pv -y
apt install proot -y
