#!/bin/bash
OS=$(uname -o)
if [[ $OS == *'Android'* ]]; then
apt install python python2 -y
pip install requests
apt install tor -y
apt install openssl openssl-tool -y
apt install php -y
apt install jq -y
gem install tail
gem install lolcat
apt install pv -y
apt install proot -y
else
sudo apt install python python2 -y
sudo apt install python3 -y
sudo pip install requests
sudo apt install tor -y
sudo apt install openssl openssl-tool -y
sudo apt install php -y
sudo apt install jq -y
sudo apt install lolcat -y
sudo apt install pv -y
fi
