#!/usr/bin/env bash
__return__ () {
source __return__ &> /dev/null
if [[ ! $? == 105 ]]
then
printf 105
fi
}

set +x

if [[ $_ == "+x" ]]
then
debug="false"
else
debug="true"
fi

__return__=$(printf "$(__return__)")

WAIT() {
sleep 0.01
}
clear

#<<<------Into~section------>>>

sleep 0.2
figlet -f slant -w 100 "please"
sleep 1
figlet -f slant -w 100 "wait"
sleep 1
echo "WELCOME!"
sleep 1
echo "to"
sleep 1
clear
figlet TSconsole
echo "Made with love"
echo "By Suman Kumar ~BHUTUU👻"
echo "<<<--------------------{t❣️s}-------------------->>>"
echo
echo
echo
echo "what's your name?"
read name

hash=759f457e8e007f79bda2dd8cea0ca476

printf "Enter your login password : "

read passd

passd=$(printf "$passd" | md5sum | awk '{printf $1}')

if [[ $hash == $passd ]]
then
  printf "Access Granted\n"

echo "welcom to TSconsole $name"

sleep 0.5


cd $PWD/Assets && python3 hack.py

else
  printf "Access Denied\n"


sleep 1
printf "press enter to exit\n"
read enter
echo "bye bye $name 😝 "
sleep 1
exit
fi
