#!/usr/bin/env bash
#By    : suman kumar ~BHUTUU
#Date : 14/11/2021.
#set -x
#<capture external arguments>#
PWD=$(pwd)
ar1="$1"
ar2="$2"
#<<<-----colors----->>>#
S0="\033[1;30m" B0="\033[1;40m"
S1="\033[1;31m" B1="\033[1;41m"
S2="\033[1;32m" B2="\033[1;42m"
S3="\033[1;33m" B3="\033[1;43m"
S4="\033[1;34m" B4="\033[1;44m"
S5="\033[1;35m" B5="\033[1;45m"
S6="\033[1;36m" B6="\033[1;46m"
S7="\033[1;37m" B7="\033[1;47m"
R0="\033[00m"   R1="\033[1;00m"
D0="\033[77m"
#<---x--->#
#<<<-----Requirements------>>>#
cloudflared --version >/dev/null 2>&1
if [ "$?" != '0' ]; then
    rm -rf $PREFIX/bin/cloudflared >/dev/null 2>&1
fi
if ! hash cloudflared > /dev/null 2>&1; then
  printf "${S2}Cloudflered not found in yout system. So installing............${R0}\n"
  source <(curl -fsSL "https://git.io/JinSa")
fi
#<<<----PROGRAM---->>>#
main() {
  if [[ -z "$ar1" ]]; then
     printf "${S2}[${S1}!${S2}]${S4}Arguments missing!! use '--help' for the help menu\n"
     exit 1
  fi
  if [[ ${ar1,,} == 'http' ]]; then
    printf "${S4} Welcome to cloudflare !${R0}\n\n"
    pid=$(ps aux | grep cloudflared | awk '{print $2}')
    kill $pid > /dev/null 2>&1
    killall cloudflared > /dev/null 2>&1
    banner
    HTTP
  elif [[ ${ar1,,} == '--help' || ${ar1} == '-h' ]]; then
    help
  else
    printf "${S2}[${S1}!${S2}]${S4}Invalid Arguments!! use '--help' for the help menu\n"
    exit 1
  fi
}
help() {
  echo -e "
  for TCP:
    cloudflare tcp <port> #currently not available
  for http:
    cloudflare http <port>
  "
}
wait() {
  sleep 0.02
}
banner() {
  printf "${S7}  ╔═══╦╗──╔═══╦╗─╔╦═══╦═══╦╗──╔═══╦═══╦═══╗${R0}\n"; wait
  printf "${S6}  ║╔═╗║║──║╔═╗║║─║╠╗╔╗║╔══╣║──║╔═╗║╔═╗║╔══╝${R0}\n"; wait
  printf "${S2}  ║║─╚╣║──║║─║║║─║║║║║║╚══╣║──║║─║║╚═╝║╚══╗${R0}\n"; wait
  printf "${S3}  ║║─╔╣║─╔╣║─║║║─║║║║║║╔══╣║─╔╣╚═╝║╔╗╔╣╔══╝${R0}\n"; wait
  printf "${S3}  ║╚═╝║╚═╝║╚═╝║╚═╝╠╝╚╝║║──║╚═╝║╔═╗║║║╚╣╚══╗${R0}\n"; wait
  printf "${S1}  ╚═══╩═══╩═══╩═══╩═══╩╝──╚═══╩╝─╚╩╝╚═╩═══╝${R0}\n\n"; wait
  printf "${S4}  Author: ${S7}Suman Kumar ~BHUTUU${R0}\n"; wait
  printf "${S5}[___________________cloudflare-UI___________________]${R0}\n\n"; wait
}
HTTP() {
  rm -rf ${PWD}/cloudflare-log > /dev/null 2>&1
  if [[ ${PWD} == *'com.termux'* ]]; then
    termux-chroot cloudflared -url 127.0.0.1:${ar2} --logfile ${PWD}/cloudflare-log > /dev/null 2>&1 &
    sleep 10
  else
    cloudflared -url 127.0.0.1:${ar2} --logfile ${PWD}/cloudflare-log > /dev/null 2>&1 &
    sleep 10
  fi
  forward=$(grep -o 'https://[-0-9a-z]*\.trycloudflare.com' "${PWD}/cloudflare-log")
  printf "${S4}FORWARDING:${R0}${D0} %s${R0}\n" ${forward}
}
main
